use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use sha2::{Digest, Sha256};
use uuid::Uuid;

use crate::{
    CoreError, CoreResult, credential,
    layout::{atomic_write_private, hex_sha256, validate_id},
    lock::LaunchLocks,
    model::{LaunchTransaction, Project, TransactionState},
    process::inspect_process,
    storage::{Storage, now},
};

pub fn register_project(storage: &Storage, source: &Path, name: &str) -> CoreResult<Project> {
    if name.trim().is_empty() || name.len() > 120 || name.chars().any(char::is_control) {
        return Err(CoreError::new("INVALID_REQUEST", "project name is invalid"));
    }
    if !source.is_absolute() {
        return Err(CoreError::new("PATH_REJECTED", "project path must be absolute"));
    }
    let canonical = fs::canonicalize(source)
        .map_err(|_| CoreError::new("PATH_REJECTED", "project path cannot be canonicalized"))?;
    if !canonical.is_dir() || canonical.starts_with(storage.layout().root()) {
        return Err(CoreError::new("PATH_REJECTED", "project source path is not allowed"));
    }
    let canonical_text = canonical
        .to_str()
        .ok_or_else(|| CoreError::new("PATH_REJECTED", "project path encoding is unsupported"))?;
    let project_id = project_id(canonical_text);
    if let Ok(existing) = storage.project(&project_id) {
        if existing.canonical_wsl_path == canonical_text {
            return Ok(existing);
        }
        return Err(CoreError::new("CONFLICT", "project identifier collision"));
    }
    let directory = storage.layout().ensure_project(&project_id)?;
    let runtime_relative_path = format!("projects/{project_id}/codex-home");
    let tmux_session_name = format!("muxlane-{}", &project_id[8..32]);
    let windows_path = windows_path(&canonical);
    let timestamp = now();
    let project = Project {
        project_id: project_id.clone(),
        name: name.trim().to_owned(),
        canonical_windows_path: windows_path,
        canonical_wsl_path: canonical_text.to_owned(),
        runtime_relative_path,
        tmux_session_name,
        active: false,
        created_at: timestamp,
        updated_at: timestamp,
    };
    let config = format!(
        "# Generated by Muxlane. Secrets are never stored here.\nproject_id = \"{}\"\n",
        project.project_id
    );
    atomic_write_private(&directory.join("codex-home/config.toml"), config.as_bytes(), false)?;
    storage.insert_project(&project)?;
    Ok(project)
}

fn project_id(canonical_path: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"muxlane-project-path-v1\0");
    hasher.update(canonical_path.as_bytes());
    format!("project_{}", hex_sha256(&hasher.finalize()))
}

fn windows_path(canonical: &Path) -> Option<String> {
    let output = Command::new("wslpath")
        .args(["-w", canonical.to_str()?])
        .stdin(Stdio::null())
        .stderr(Stdio::null())
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout).ok().map(|value| value.trim().to_owned())
}

pub fn prepare_launch(
    storage: &Storage,
    account_id: &str,
    project_id: &str,
) -> CoreResult<LaunchTransaction> {
    validate_id(account_id)?;
    validate_id(project_id)?;
    storage.account(account_id)?;
    storage.project(project_id)?;
    if storage.has_open_incident(project_id)? {
        return Err(CoreError::new(
            "RECOVERY_REQUIRED",
            "project has an unresolved recovery incident",
        ));
    }
    let _locks = LaunchLocks::try_acquire(storage.layout(), account_id, project_id)?;
    if credential::runtime_auth_exists(storage.layout(), project_id)? {
        return Err(CoreError::new(
            "RECOVERY_REQUIRED",
            "project Runtime contains an unresolved active credential",
        ));
    }
    let timestamp = now();
    let transaction = LaunchTransaction {
        transaction_id: format!("transaction_{}", Uuid::new_v4().simple()),
        launch_id: format!("launch_{}", Uuid::new_v4().simple()),
        project_id: project_id.to_owned(),
        account_id: account_id.to_owned(),
        state: TransactionState::Preparing,
        runner_pid: None,
        codex_pid: None,
        boot_id: None,
        runner_start_ticks: None,
        codex_start_ticks: None,
        runner_identity: None,
        codex_identity: None,
        vault_hash_before_checkout: None,
        runtime_hash_at_checkout: None,
        runtime_hash_at_recovery: None,
        vault_hash_at_recovery: None,
        credential_backup_reference: None,
        last_error_code: None,
        last_error_message_redacted: None,
        recovery_attempts: 0,
        created_at: timestamp,
        updated_at: timestamp,
    };
    storage.create_launch(&transaction)?;
    Ok(transaction)
}

pub fn run_managed_launch(storage: &Storage, transaction_id: &str) -> CoreResult<i32> {
    let transaction = storage.transaction(transaction_id)?;
    if transaction.state != TransactionState::Preparing {
        return Err(CoreError::new(
            "INVALID_STATE",
            "managed runner cannot enter this transaction",
        ));
    }
    let _locks = LaunchLocks::try_acquire(
        storage.layout(),
        &transaction.account_id,
        &transaction.project_id,
    )?;
    if let Err(error) = credential::checkout(storage, transaction_id) {
        storage.fail(transaction_id, error.code, &error.message)?;
        return Err(error);
    }
    let project = storage.project(&transaction.project_id)?;
    let codex_home = storage.layout().codex_home(&transaction.project_id)?;
    let mut child = match Command::new("codex")
        .current_dir(&project.canonical_wsl_path)
        .env("CODEX_HOME", &codex_home)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .spawn()
    {
        Ok(child) => child,
        Err(_) => {
            let disposition = credential::commit_and_clean(storage, transaction_id)?;
            if disposition != credential::CredentialDisposition::Conflict {
                storage.transition(transaction_id, TransactionState::Recovered)?;
                storage.finish_launch(transaction_id, "codex_start_failed")?;
            }
            return Err(CoreError::new("CODEX_UNAVAILABLE", "Codex CLI could not be started"));
        }
    };
    let identities = inspect_process(std::process::id())
        .and_then(|runner| inspect_process(child.id()).map(|codex| (runner, codex)));
    let (runner_identity, codex_identity) = match identities {
        Ok(identities) => identities,
        Err(error) => {
            let _ = child.kill();
            let _ = child.wait();
            let cleanup = credential::commit_and_clean(storage, transaction_id);
            if let Err(cleanup_error) = cleanup {
                storage.fail(transaction_id, cleanup_error.code, &cleanup_error.message)?;
                return Err(cleanup_error);
            }
            storage.fail(transaction_id, error.code, &error.message)?;
            return Err(error);
        }
    };
    storage.record_processes(transaction_id, &runner_identity, &codex_identity)?;
    let status = child
        .wait()
        .map_err(|_| CoreError::new("PROCESS_IDENTITY_UNCONFIRMED", "Codex process wait failed"))?;
    storage.transition(transaction_id, TransactionState::CodexExited)?;
    let disposition = credential::commit_and_clean(storage, transaction_id)?;
    if disposition != credential::CredentialDisposition::Conflict {
        storage.transition(transaction_id, TransactionState::Finished)?;
        storage.finish_launch(
            transaction_id,
            if status.success() { "exited" } else { "exited_error" },
        )?;
    }
    Ok(status.code().unwrap_or(128))
}

pub fn resolve_executable_for_runner() -> CoreResult<PathBuf> {
    let executable = std::env::current_exe().map_err(|_| {
        CoreError::new("CODEX_UNAVAILABLE", "daemon executable path is unavailable")
    })?;
    if !executable.is_absolute() {
        return Err(CoreError::new("PATH_REJECTED", "daemon executable path is not absolute"));
    }
    Ok(executable)
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn stable_project_ids_isolate_same_names_at_different_paths() {
        let temp = tempdir().unwrap();
        let first = temp.path().join("one");
        let second = temp.path().join("two");
        fs::create_dir(&first).unwrap();
        fs::create_dir(&second).unwrap();
        let layout = crate::layout::Layout::initialize(temp.path().join("runtime")).unwrap();
        let storage = Storage::open(layout).unwrap();
        let first = register_project(&storage, &first, "same").unwrap();
        let second = register_project(&storage, &second, "same").unwrap();
        assert_ne!(first.project_id, second.project_id);
        assert_ne!(first.runtime_relative_path, second.runtime_relative_path);
        assert_ne!(first.tmux_session_name, second.tmux_session_name);
    }
}
