//! Future protocol boundary for Muxlane components.
//!
//! The only wire types defined here are explicitly scoped to the non-production
//! Phase 3 terminal POC. They are not a stable Runtime or RPC protocol.

#![forbid(unsafe_code)]

use serde::{Deserialize, Serialize};

/// Stable package identifier for build and integration checks.
pub const CRATE_IDENTIFIER: &str = "muxlane-protocol";

/// A request sent over the POC's local stdio bridge.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Phase3Request {
    Probe,
    CreateSyntheticSession { project_id: String },
    ListManagedSessions,
    CreateWindow { project_id: String, name: String },
    ListWindows { project_id: String },
    Attach { project_id: String, window_id: String },
    Detach,
    SendInput { bytes: Vec<u8> },
    Resize { columns: u16, rows: u16 },
    CloseWindow { project_id: String, window_id: String },
    CleanupSession { project_id: String },
    ReadState,
}

/// A request envelope permits the host to match a structured response.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct Phase3RequestEnvelope {
    pub id: u64,
    pub request: Phase3Request,
}

/// A managed session. The name is generated by the gateway, never supplied as a tmux target.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct ManagedSession {
    pub project_id: String,
    pub session_name: String,
    pub session_id: String,
}

/// A window discovered from a session that has already passed managed-session validation.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct ManagedWindow {
    pub id: String,
    pub name: String,
    pub active: bool,
}

/// Control-plane results for the POC bridge.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Phase3Response {
    Probe { tmux_version: String },
    Sessions { sessions: Vec<ManagedSession> },
    Windows { windows: Vec<ManagedWindow> },
    Attached { project_id: String, window_id: String },
    Detached,
    State { attached: Option<AttachedTerminal> },
    Acknowledged,
}

/// The current data-plane attachment, if any.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct AttachedTerminal {
    pub project_id: String,
    pub window_id: String,
}

/// Structured failures intentionally omit child-process stderr and terminal content.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct Phase3Error {
    pub code: String,
    pub message: String,
}

/// Data-plane events; output is raw bytes to avoid conflating UTF-8 with terminal bytes.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Phase3Event {
    History { bytes: Vec<u8> },
    Output { bytes: Vec<u8> },
    StreamClosed,
    StreamError { code: String },
}

/// Every stdout frame is a typed response or terminal event, never a free-form command.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "frame", rename_all = "snake_case")]
pub enum Phase3Frame {
    Response {
        id: u64,
        #[serde(flatten)]
        result: ResultFrame,
    },
    Event {
        event: Phase3Event,
    },
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum ResultFrame {
    Ok { response: Phase3Response },
    Error { error: Phase3Error },
}

#[cfg(test)]
mod tests {
    use super::{Phase3Frame, Phase3Request, Phase3RequestEnvelope};

    #[test]
    fn phase3_poc_frames_are_typed_and_round_trip() {
        let request = Phase3RequestEnvelope {
            id: 7,
            request: Phase3Request::Resize { columns: 120, rows: 40 },
        };
        let encoded = serde_json::to_string(&request).expect("serializes test request");
        let decoded: Phase3RequestEnvelope =
            serde_json::from_str(&encoded).expect("deserializes test request");
        assert_eq!(decoded, request);

        let malformed = r#"{\"id\":1,\"request\":{\"kind\":\"execute\",\"command\":\"id\"}}"#;
        assert!(serde_json::from_str::<Phase3RequestEnvelope>(malformed).is_err());
        assert!(
            serde_json::to_string(&Phase3Frame::Event { event: super::Phase3Event::StreamClosed })
                .is_ok()
        );
    }
}
